// libs/vue/range-selector/src/lib/RangeSelector.vue
<template>
  <Teleport to="body">
    <div class="container" v-if="show"></div>
  </Teleport>
</template>

<script setup lang="ts">
import {extendRectangle, RectangleCoordinate, RectanglePointPosition} from "@how-to-make/shared/range-selector";
import {useRef} from "react";
import {onMounted, onUnmounted} from "vue";

const show = useRef(false);
const rectangleCoordinate = useRef<RectangleCoordinate>()
let fixedPoint: RectanglePointPosition | undefined;

function onMouseDown() {
  function onMouseUp() {
    clear();
    window.removeEventListener('mousemove', onMouseMove);
    window.removeEventListener('mouseup', onMouseUp);
  }

  function onMouseMove(event: { pageX: number, pageY: number }) {
    const {pageX, pageY} = event;

    if (fixedPoint) {
      rectangleCoordinate.current = extendRectangle(fixedPoint, {left: pageX, top: pageY});

    } else {
      fixedPoint = {top: pageY, left: pageX};
      show.current = true;
    }
  }

  window.addEventListener('mouseup', onMouseUp);
  window.addEventListener('mousemove', onMouseMove);
}

function clear() {
  show.current = false;
  fixedPoint = undefined;
}

onMounted(() => {
  window.addEventListener('mousedown', onMouseDown);
});

onUnmounted(() => {
  window.removeEventListener('mousedown', onMouseDown);
  clear();
});

</script>

<style module>
.container {
  box-shadow: 0 0 5px rgb(0 0 0 / 10%);
  background-color: rgba(0, 0, 0, 0.1);
  border: 1px solid #d4d4d4;
  pointer-events: none;
  position: fixed;
  z-index: 500;
}
</style>

// libs/react/range-selector/src/lib/react-range-selector.tsx
import styles from './react-range-selector.module.scss';
import {useEffect, useRef, useState} from "react";
import {createPortal} from "react-dom";
import {extendRectangle, RectangleCoordinate, RectanglePointPosition} from "../../../../shared/range-selector/range-selector";


/* eslint-disable-next-line */
export interface ReactRangeSelectorProps {
  boundary?: HTMLElement
}

export function ReactRangeSelector(props: ReactRangeSelectorProps) {
  const fixedPosition = useRef<RectanglePointPosition>();
  const [visible, setVisible] = useState<boolean>(false);
  const [rectangleCoordinate, setRectangleCoordinate] = useState<RectangleCoordinate>();

  useEffect(() => {
    function clear() {
      fixedPosition.current = undefined;
      setRectangleCoordinate(undefined);
      setVisible(false);
    }

    function onMouseDown() {
      window.addEventListener('mouseup', onMouseUp);
      window.addEventListener('mousemove', onMouseMove);
    }

    function onMouseMove(event: any) {
      if (fixedPosition.current) {
        setRectangleCoordinate(extendRectangle(fixedPosition.current, {top: event.pageY, left: event.pageX}));
      } else {
        fixedPosition.current = {
          left: event.pageX,
          top: event.pageY,
        };

        setVisible(true);
      }
    }

    function onMouseUp() {
      window.removeEventListener('mouseup', onMouseUp);
      window.removeEventListener('mousemove', onMouseMove);
      clear();
    }

    const boundary = props.boundary || window;

    boundary.addEventListener('mousedown', onMouseDown);

    return () => {
      boundary.removeEventListener('mousedown', onMouseDown);
      clear();
    }
  }, [props.boundary]);

  return createPortal(visible ?
    <div style={rectangleCoordinate} className={styles['container']}></div> : undefined, document.body);

}

export default ReactRangeSelector;
