// apps/vue/src/components/RangeSelectorExample.vue
<template>
  <div className={styles['container']}>
    <div className={styles['box-item-container']}>
      <div className={styles['box-item']}></div>
      <div className={styles['box-item']}></div>
      <div className={styles['box-item']}></div>
    </div>

    <ReactRangeSelector></ReactRangeSelector>
  </div>

</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'range-selector-example',
});
</script>

<style scoped lang="scss"></style>

// apps/angular/src/app/angular-range-selector-example/angular-range-selector-example.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  AngularRangeSelectorComponent
} from "../../../../../libs/angular/range-selector/src/lib/angular-range-selector/angular-range-selector.component";

@Component({
  selector: 'angular-range-selector-example',
  standalone: true,
  imports: [CommonModule, AngularRangeSelectorComponent],
  templateUrl: './angular-range-selector-example.component.html',
  styleUrls: ['./angular-range-selector-example.component.scss'],
})
export class AngularRangeSelectorExampleComponent {}

<div class="container">
  <div class="box-item-container">
    <div class="box-item"></div>
    <div class="box-item"></div>
    <div class="box-item"></div>
  </div>
  <angular-range-selector></angular-range-selector>
</div>
