// apps/react/src/app/range-selector-example/range-selector-example.tsx
import styles from './range-selector-example.module.scss';
import {ReactRangeSelector} from "dist";
import {useCallback} from "react";
import {RangeSelectorIntersectionChangeEvent} from "@how-to-make/shared/range-selector";

/* eslint-disable-next-line */
export interface BoxSelectorProps {
}

export function RangeSelectorExample(props: BoxSelectorProps) {

  const onIntersectionChange = useCallback((event: RangeSelectorIntersectionChangeEvent) => {
      if (event.haveIntersection) {
        event.node.classList.add(styles['--active']);
      } else {
        event.node.classList.remove(styles['--active']);
      }
  }, [])


  return (
    <div className={styles['container']}>
      <div className={styles['box-container']}>
        <div className={styles['box-item']}></div>
        <div className={styles['box-item']}></div>
        <div className={styles['box-item']}></div>
      </div>

      <ReactRangeSelector
        intersectionChange={(event) => onIntersectionChange(event)}
        intersectionElementSelector={'[class*="box-item"]'}></ReactRangeSelector>
    </div>
  );
}

export default RangeSelectorExample;

// apps/vue/src/views/RangeSelectorExample.vue
<template>
  <div class="container">
    <div class="box-item-container">
      <div class="box-item"></div>
      <div class="box-item"></div>
      <div class="box-item"></div>
    </div>
    <RangeSelector intersection-element-selector=".box-item" @intersectionChange="($event)=> onIntersectionChange($event)"/>
  </div>
</template>

<script setup lang="ts">
import RangeSelector from "libs/vue/range-selector/src/lib/VueRangeSelector.vue";
import {RangeSelectorIntersectionChangeEvent} from "@how-to-make/shared/range-selector";

const onIntersectionChange = (event: RangeSelectorIntersectionChangeEvent) => {
  if (event.haveIntersection) {
    event.node.classList.add('--active');
  } else {
    event.node.classList.remove('--active');
  }
}
</script>

<style scoped lang="scss">
.container {
  width: 100%;
  height: 100%;
  padding: 16px;
}

.box-item-container {
  display: flex;
  align-items: center;
  justify-content: center;
}

.box-item {
  width: 120px;
  height: 300px;
  background: #e0e0e0;
  margin: 8px;
  opacity: 0.8;
}

.--active {
  background-color: #00BCD4;
}

</style>
