// apps/vue/src/components/RangeSelectorExample.vue
<template>
  <div className={styles['container']}>
    <div className={styles['box-item-container']}>
      <div className={styles['box-item']}></div>
      <div className={styles['box-item']}></div>
      <div className={styles['box-item']}></div>
    </div>

    <ReactRangeSelector></ReactRangeSelector>
  </div>

</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'range-selector-example',
});
</script>

<style scoped lang="scss"></style>

// apps/react/src/app/range-selector-example/range-selector-example.tsx
import styles from './range-selector-example.module.scss';
import {ReactRangeSelector} from "dist";

/* eslint-disable-next-line */
export interface BoxSelectorProps {
}

export function RangeSelectorExample(props: BoxSelectorProps) {
  return (
    <div className={styles['container']}>
      <div className={styles['box-item-container']}>
        <div className={styles['box-item']}></div>
        <div className={styles['box-item']}></div>
        <div className={styles['box-item']}></div>
      </div>

      <ReactRangeSelector></ReactRangeSelector>
    </div>
  );
}

export default RangeSelectorExample;
